version: '3.8'

services:

  ms-sql:
   image: mcr.microsoft.com/mssql/server:2019-latest
   container_name: sql2k19_01_qa01
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=qaSqlPwd01A
    - TZ=America/New_York
    - MSSQL_PID=Developer
   ports:
    - "1435:1435"
