version: '3.8'

services:

  ms-sql:
   image: mcr.microsoft.com/mssql/server:2019-latest
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=qaSqlPwd01A
    - TZ=America/New_York
    - MSSQL_PID=Developer

